/* =========================================================================
   Builds the NASIJ WordPress theme from the static site.
     node wordpress/build.js
   → dist/wordpress/nasij/           (the theme folder)
   → dist/nasij-wordpress-theme.zip  (upload in wp-admin → Appearance → Themes)
   The same assets/ run on GitHub Pages and on WordPress; the theme only adds
   index.php / dashboard.php shells (generated from index.html / admin.html)
   and functions.php (REST API + database tables + /nasij-admin/ route).
   ========================================================================= */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const OUT_BASE = path.join(ROOT, 'dist', 'wordpress');
const OUT = path.join(OUT_BASE, 'nasij');
const LITE = process.argv.includes('--lite'); /* code only, for quick tests */
const ZIP = path.join(ROOT, 'dist', LITE ? 'nasij-wordpress-theme-lite.zip' : 'nasij-wordpress-theme.zip');
let sharp = null;
try { sharp = require(path.resolve(ROOT, '..', 'the-9-menu', 'node_modules', 'sharp')); } catch (e) { try { sharp = require('sharp'); } catch (e2) { /* optional */ } }

const rm = p => fs.rmSync(p, { recursive: true, force: true });
const mk = p => fs.mkdirSync(p, { recursive: true });
function copyDir(src, dst) { mk(dst); for (const f of fs.readdirSync(src, { withFileTypes: true })) { const a = path.join(src, f.name), b = path.join(dst, f.name); if (f.isDirectory()) copyDir(a, b); else fs.copyFileSync(a, b); } }

const T = "<?php echo esc_url( get_template_directory_uri() ); ?>/";
const HOME = "<?php echo esc_url( home_url( '/' ) ); ?>";
const LIVE = 'https://mohamed-sr-designer.github.io/nasij/';
const guard = doc => `<?php\n/**\n * ${doc}\n *\n * Generated by wordpress/build.js from the static site — edit the source, then rebuild.\n *\n * @package nasij\n */\n\nif ( ! defined( 'ABSPATH' ) ) {\n\texit;\n}\n?>`;
const assetUrls = h => h.replace(/(href|src)="(assets|images)\//g, (m, a, b) => a + '="' + T + b + '/');

async function main() {
  rm(OUT); rm(ZIP); mk(OUT);

  // 1) theme source files
  copyDir(path.join(__dirname, 'theme'), OUT);

  // 2) storefront + dashboard code
  copyDir(path.join(ROOT, 'assets'), path.join(OUT, 'assets'));

  // 3) images that the site references (defaults, code, shells) + logos
  const scan = ['assets/js/defaults.js', 'assets/js/store.js', 'assets/js/core.js', 'index.html', 'admin.html', 'assets/js/admin/app.js', 'assets/js/admin/views-store.js', 'assets/js/admin/views-commerce.js'];
  const used = new Set(['images/logo-en.png', 'images/logo-en-white.png', 'images/logo-ar.png', 'images/logo-ar-white.png']);
  scan.forEach(f => { const txt = fs.readFileSync(path.join(ROOT, f), 'utf8'); (txt.match(/images\/[A-Za-z0-9_\/.-]+\.(?:jpe?g|png|webp|gif|svg)/g) || []).forEach(u => used.add(u)); });
  let bytes = 0, n = 0;
  for (const u of used) {
    if (LITE && !/logo/.test(u)) continue;
    const src = path.join(ROOT, u), dst = path.join(OUT, u);
    if (!fs.existsSync(src)) continue;
    mk(path.dirname(dst));
    const big = fs.statSync(src).size > 350 * 1024 && /\.jpe?g$/i.test(u);
    if (sharp && big) await sharp(src).jpeg({ quality: 82, mozjpeg: true }).toFile(dst);
    else fs.copyFileSync(src, dst);
    bytes += fs.statSync(dst).size; n++;
  }

  // 4) PHP shells
  let idx = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  idx = idx.split(LIVE + 'images/').join(T + 'images/').split(LIVE).join(HOME);
  idx = assetUrls(idx);
  idx = idx.replace(/<link rel="manifest"[^>]*>\n?/, '');
  idx = idx.replace('<script src="' + T + 'assets/js/defaults.js', () => '<?php nasij_config( false ); ?>\n<script src="' + T + 'assets/js/defaults.js');
  idx = idx.replace('</head>', () => '<?php wp_head(); ?>\n</head>').replace('</body>', () => '<?php wp_footer(); ?>\n</body>');
  fs.writeFileSync(path.join(OUT, 'index.php'), guard('Storefront shell. Every page (#/shop, #/products/…) is rendered in the browser by assets/js/store.js.') + idx);

  let adm = fs.readFileSync(path.join(ROOT, 'admin.html'), 'utf8');
  adm = assetUrls(adm);
  adm = adm.replace('<script src="' + T + 'assets/js/defaults.js', () => '<?php nasij_config( true ); ?>\n<script src="' + T + 'assets/js/defaults.js');
  fs.writeFileSync(path.join(OUT, 'dashboard.php'), guard('Dashboard shell, served at /nasij-admin/ to Administrators and Editors (see functions.php).') + adm);

  // 5) zip (forward-slash entries so it unpacks correctly on Linux hosts)
  if (process.platform === 'win32') execFileSync('C:\\Windows\\System32\\tar.exe', ['-a', '-c', '-f', ZIP, '-C', OUT_BASE, 'nasij']);
  else execFileSync('zip', ['-qr', ZIP, 'nasij'], { cwd: OUT_BASE });

  console.log(`theme → ${path.relative(ROOT, OUT)}  (${n} images, ${(bytes / 1048576).toFixed(1)} MB)`);
  console.log(`zip   → ${path.relative(ROOT, ZIP)}  (${(fs.statSync(ZIP).size / 1048576).toFixed(1)} MB)`);
}
main().catch(e => { console.error(e); process.exit(1); });
